### PR TITLE
Import timestamp from utils

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by wdpypere** [comment]
@itkovian thank you for looking in to this. Does this supersede https://github.com/hpcugent/vsc-administration/pull/66 (e.g. can that one be closed?)

**Comment by wdpypere** [comment]
and 2 minor pep8 issues ;)

**Comment by itkovian** [comment]
Ah dang :) Euh, #66 is better than.

**Comment by itkovian** [comment]
I'll take over @JensTimmerman's his changes here.

**Comment by wdpypere** [comment]
one more pep8 issue remaining, almost there!

**Comment by itkovian** [comment]
I do not see any long lines in that file ..

**Comment by itkovian** [comment]
Closes #66

**Pull request merged**
